#! /usr/bin/sh
#
# Copyright (c) 2021 Kentaro Hara
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

cd `dirname $0`
cd ..
mkdir -p ./log
./test/run_coin_bond_unittest.py > ./log/truffle_coin_bond_unittest.log
./test/run_logging_unittest.py > ./log/truffle_logging_unittest.log
#./test/run_oracle_unittest.py > ./log/truffle_oracle_unittest.log
#./test/run_oracle_simulator.py > ./log/truffle_oracle_simulator.log
./test/run_bond_operation_unittest.py > ./log/truffle_bond_operation_unittest.log
./test/run_open_market_operation_unittest.py > ./log/truffle_open_market_operation_unittest.log
./test/run_acb_unittest.py > ./log/truffle_acb_unittest.log
./test/run_acb_simulator.py > ./log/truffle_acb_simulator.log
#./test/run_acb_upgrade.py > ./log/truffle_acb_upgrade.log
