#! /usr/bin/sh
#
# Copyright (c) 2021 Kentaro Hara
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

cd `dirname $0`
mkdir -p ../log
./coin_bond_unittest.py > ../log/python_coin_bond_unittest.log
./logging_unittest.py > ../log/python_logging_unittest.log
./oracle_unittest.py > ../log/python_oracle_unittest.log
./oracle_simulator.py > ../log/python_oracle_simulator.log
./acb_unittest.py > ../log/python_acb_unittest.log
./acb_simulator.py > ../log/python_acb_simulator.log

